# Generated by Django 5.0.2 on 2024-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='end_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год окончания выпуска'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год начала выпуска'),
        ),
    ]
