# Generated by Django 5.0.2 on 2024-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0002_alter_automobile_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания выпуска'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала выпуска'),
        ),
    ]
