# Generated by Django 5.0.2 on 2024-02-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0003_alter_automobile_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.automobile', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.country', verbose_name='Страна'),
        ),
    ]
